name: Test

on:
  push:
    branches:
      - '*'
      - '!master'

env:
  PYTHON_VERSION: 3.8.3


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    name: Python ${{ matrix.python-version }} test

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install poetry
        run: pip install poetry

      - name: install deps
        run: poetry install

      - name: test
        run: poetry run pytest --cache-clear --cov=src > pytest-coverage.txt

      - name: Pytest coverage comment
        if: matrix.python-version == '3.11'
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
